### ISSUE TITLE
Cmd line marteau requires running redis server

### ISSUE THREAD

**Issue by rafrombrc** [mozilla-services/marteau#20]
When running `marteau /path/to/loadtest/repo` from a command line I get the following traceback, which is apparently not supposed to happen when running from the command line:

```
Traceback (most recent call last):
  File "/home/rob/venv/marteau/bin/marteau", line 9, in <module>
    load_entry_point('marteau==0.1', 'console_scripts', 'marteau')()
  File "/home/rob/venv/marteau/marteau/marteau/job.py", line 372, in main
    fixture_options=args.fixture_options)
  File "/home/rob/venv/marteau/marteau/marteau/job.py", line 104, in _std
    return func(*args, **kwargs)
  File "/home/rob/venv/marteau/marteau/marteau/job.py", line 116, in _cleanup
    return func(*args, **kwargs)
  File "/home/rob/venv/marteau/marteau/marteau/job.py", line 147, in run_loadtest
    _logrun('Moved to %r' % repo)
  File "/home/rob/venv/marteau/marteau/marteau/job.py", line 58, in _logrun
    sys.stderr.write(msg)
  File "/home/rob/venv/marteau/marteau/marteau/job.py", line 50, in write
    job_id = self._queue.pid_to_jobid(os.getpid())
  File "/home/rob/venv/marteau/marteau/marteau/queue.py", line 20, in pid_to_jobid
    return self._conn.get('retools:jobpid:%s' % str(pid))
  File "/home/rob/venv/marteau/local/lib/python2.7/site-packages/redis-2.7.2-py2.7.egg/redis/client.py", line 551, in get
    return self.execute_command('GET', name)
  File "/home/rob/venv/marteau/local/lib/python2.7/site-packages/redis-2.7.2-py2.7.egg/redis/client.py", line 364, in execute_command
    connection.send_command(*args)
  File "/home/rob/venv/marteau/local/lib/python2.7/site-packages/redis-2.7.2-py2.7.egg/redis/connection.py", line 301, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/rob/venv/marteau/local/lib/python2.7/site-packages/redis-2.7.2-py2.7.egg/redis/connection.py", line 283, in send_packed_command
    self.connect()
  File "/home/rob/venv/marteau/local/lib/python2.7/site-packages/redis-2.7.2-py2.7.egg/redis/connection.py", line 231, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting localhost:6379. Connection refused.
```

**Comment by tarekziade** [comment]
For now I am making redis mandatory. The whole code depends on queue and we need to implement a memory fallback, which is not a big priority
